### ISSUE TITLE
"Unexpected token <" error in browser

### ISSUE THREAD

**Issue by darkadept** [jedwards1211/crater#12]
Getting this error in the browser console in a fresh-from-git version: "app.js:1 Uncaught SyntaxError: Unexpected token <".

**Comment by jedwards1211** [comment]
Sorry, I changed the dev server port to 4000, so that the dev server could run separately and not be restarted when the server code changes.  Try localhost:4000

**Comment by darkadept** [comment]
Ahh yes. Duh, it's in the README. I didn't catch the change. Thanks.

**Comment by jedwards1211** [comment]
Yeah, I should probably start a changelog before long
