### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by shijunti19** [jedwards1211/crater#2]
F:\web\xiaolu\meteor\a031\a031_semantic\crater>npm -v
3.8.9
F:\web\xiaolu\meteor\a031\a031_semantic\crater>node -v
v6.2.1
meteor update
npm start
**windows10**
BUG：
F:\web\xiaolu\meteor\a031\a031_semantic\crater>npm start

> crater@1.0.0-alpha.0 start F:\web\xiaolu\meteor\a031\a031_semantic\crater
> NODE_ENV=development node src/server/index.js

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! crater@1.0.0-alpha.0 start: `NODE_ENV=development node src/server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crater@1.0.0-alpha.0 start script 'NODE_ENV=development node src/server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the crater package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node src/server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs crater
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls crater
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\web\xiaolu\meteor\a031\a031_semantic\crater\npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.8.9
3 info using node@v6.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle crater@1.0.0-alpha.0~prestart: crater@1.0.0-alpha.0
6 silly lifecycle crater@1.0.0-alpha.0~prestart: no script for prestart, continuing
7 info lifecycle crater@1.0.0-alpha.0~start: crater@1.0.0-alpha.0
8 verbose lifecycle crater@1.0.0-alpha.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle crater@1.0.0-alpha.0~start: PATH: E:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\web\xiaolu\meteor\a031\a031_semantic\crater\node_modules\.bin;E:\Program Files\nodejs;C:\Program Files (x86)\Common Files\NetSarang;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;E:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;E:\Program Files\AOMEI Backupper 2.1;F:\web\UPUPW_K2.0_64\PHPX\PHP70;C:\ProgramData\ComposerSetup\bin;E:\Program Files\nodejs\;E:\Program Files\Git\cmd;E:\Program Files\Python27;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;E:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\xiaolu\AppData\Roaming\Composer\vendor\bin;C:\Users\xiaolu\AppData\Roaming\npm;C:\Users\xiaolu\AppData\Local\.meteor\
10 verbose lifecycle crater@1.0.0-alpha.0~start: CWD: F:\web\xiaolu\meteor\a031\a031_semantic\crater
11 silly lifecycle crater@1.0.0-alpha.0~start: Args: [ '/d /s /c', 'NODE_ENV=development node src/server/index.js' ]
12 silly lifecycle crater@1.0.0-alpha.0~start: Returned: code: 1  signal: null
13 info lifecycle crater@1.0.0-alpha.0~start: Failed to exec start script
14 verbose stack Error: crater@1.0.0-alpha.0 start: `NODE_ENV=development node src/server/index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (E:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (E:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid crater@1.0.0-alpha.0
16 verbose cwd F:\web\xiaolu\meteor\a031\a031_semantic\crater
17 error Windows_NT 10.0.10240
18 error argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.2.1
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error crater@1.0.0-alpha.0 start: `NODE_ENV=development node src/server/index.js`
22 error Exit status 1
23 error Failed at the crater@1.0.0-alpha.0 start script 'NODE_ENV=development node src/server/index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the crater package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=development node src/server/index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs crater
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls crater
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

My app is :meteor 1.4.1+react
My original frame for this：
https://github.com/thereactivestack/kickstart-meteor-react-router
I want you to try this!

**Comment by jedwards1211** [comment]
Ah, I haven't tested it on Node 6 yet.  Let me see...

**Comment by jedwards1211** [comment]
Oh, it's because the npm scripts aren't written for Windows command line.  Do you have 64-bit Windows?  If so please try running with [Linux Bash Shell on Windows 10](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/).

**Comment by jedwards1211** [comment]
Actually this is a better installation guide: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by jedwards1211** [comment]
You could also try using Cygwin

**Comment by jedwards1211** [comment]
Hi @shijunti19, I just rewrote all the scripts to support windows -- sorry for the delay.  It should work for you now!

**Comment by java99** [comment]
Similar issue here: System: Windows Server 2012

/cygdrive/c/SHS4
$ npm start

> SHS4@0.2.0 start C:\SHS4
> babel-node scripts/start.js

build/meteor is up to date
installing Meteor npm dependencies...
Error: spawn C:\Windows\System32\cmd.exe ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                   node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.1
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! SHS4@0.2.0 start: `babel-node scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SHS4@0.2.0 start script 'babel-node scripts/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the SHS4 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node scripts/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs SHS4
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls SHS4
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\SHS4\npm-debug.log

Any idea what is causing this?
