### ISSUE TITLE
Question: Does the meteor dev database run?

### ISSUE THREAD

**Issue by darkadept** [jedwards1211/crater#5]
When running in dev mode, does the meteor database also run?

I'm assuming you need to have your own database configured? Also, how does one go about connecting meteor to the database? It might be a good addition to the README.

**Comment by jedwards1211** [comment]
Whoops, good question, I forgot to mention that -- you have to run `mongod` yourself in a separate shell.

**Comment by jedwards1211** [comment]
The connection is configured by the `MONGO_URL` environment variable, which I put in the `.env` file.
